### ISSUE TITLE
@pedroaf0 to-do list

### ISSUE THREAD

**Issue by pedroaf0** [Mateusbertolini/proof_of_concept#1]
# Integrações
- [x] Consultar paciente
- [x] Criar paciente
- [x] Pagina do paciente
# Deploy
- [x] Criar repositório próprio do backend
- [x] Configurar repositório no servidor  [https://prontuario-ufpel-backend.onrender.com/](https://prontuario-ufpel-backend.onrender.com/)
_Nota: Agora o heroku pede cartão de crédito para criar novos apps, mas como eu tenho apps antigos já criados posso usar eles para criar o servidor sem precisar incluir um cartão_
- [x] Incluir link do servidor nas paginas integradas
